### ISSUE TITLE
Document Robot Controls

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#19]
**How does this improve the robot or repo?**
* Easier to introduce new drivers to the controls of the robot.

**Feature Description**
* Document the robot controls in a Markdown document (in a table), and...
* Label the controls on a picture of an Xbox controller for both the operator and driver.

**Potential Implementation**
* See [Charged-Up-2023](https://github.com/frc2609/Charged-Up-2023/blob/main/docs/Robot%20Instructions.md#driver) for an example on how to describe the robot controls in a Markdown file.
* To label the controls on an Xbox controller, get an image of an Xbox controller, and add labels to it using image editing software (e.g. Google Drawings).

**Comment by gregzetko** [comment]
Adding this to Durham milestone as it depends on the "All mechanisms functional" milestone

**Comment by UserC2** [comment]
Closing as not planned as this isn't a particularly high priority and the controls keep changing
