### ISSUE TITLE
Clean up unused branches

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#26]
* `shooter-flywheel`: Awaiting testing on robot before merging pull request
* `SnapToApriltag`: @WhyNot180 @newjanson status?
* `kraken-swerve`: Require robot to be wired to finish configuration, then it needs to be tested.
* `apriltags`: @newjanson status?
* `beaversight`: @newjanson status?

**Comment by WhyNot180** [comment]
SnapToApriltag needs some cleanup and docs added, but should otherwise be good for a PR.

apriltags is abandoned AFAIK.

**Comment by gregzetko** [comment]
apriltags and beaversight should be abandoned. SnapToApriltag needs some cleanup and docs as @WhyNot180 mentioned

**Comment by UserC2** [comment]
Will see if anything useful is hiding in apriltags and beaversight, if not I'll delete them and close this issue.

**Comment by UserC2** [comment]
Removed branches.
