### ISSUE TITLE
Automatic note pickup command

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#27]
**How does this improve the robot or repo?**
* More reliable note pickup during autonomous (if tuned properly)

**Feature Description**
* (Separately, an autonomous path brings the robot in front of the note)
* Rotate to face note using Limelight
* Drive forward and enable intake
* End once intake detects note picked up (or after a certain time delay in case the sensor fails)

**Comment by gregzetko** [comment]
with the current iteration of our intake, we don't have real estate for a front-facing limelight :(

**Comment by UserC2** [comment]
> with the current iteration of our intake, we don't have real estate for a front-facing limelight :(

:(

Also do we have space to mount the limelight in front of one of the swerve modules?

**Comment by UserC2** [comment]
Limelight being added by @newjanson

**Comment by UserC2** [comment]
Closing as not planned (for now) as Limelight has been removed
