### ISSUE TITLE
Backup shooting presets

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#3]
**How does this improve the robot or repo?**
Allows the ability to score if automatic scoring breaks down.

**Feature Description**
* Two known shooter presets for "contingencies".
  * One for right up against the speaker
  * One with the back of the robot against the podium.

* Optionally, another preset for "close-ish" to the shooter so we can shoot from ~2 meters away. (If implemented, it should work +- 0.5m so it's actually usable.)

**Potential Implementation**
Two buttons hardcoded to a shooter setpoint.

**Comment by gregzetko** [comment]
This is a good starting point, as well as a good failsafe! It is critical that we finish this before going to any kind of scrimmage/practice/competition.

**Comment by gregzetko** [comment]
Additionally, these contingencies should include resetting the odometry to the known preset positions. This will allow us to use "auto-alignment" again until the odometry goes off course again
