### ISSUE TITLE
Manual control for subsystems controlled by PIDF

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#32]
**How does this improve the robot or repo?**
* Allows (some) functionality to be retained if the automatic control of a subsystem fails.

**Feature Description**
* Directly control motors with joystick input from operator controller **when the manual control is enabled**.
* Manual override for mechanism safety limits (e.g. on shooter angle; useful if absolute encoder fails)

**Comment by gregzetko** [comment]
Perhaps also include a switch to a redundant sensor? e.g. fall back to some kind of a neo encoder control loop if the absolute encoder fails

**Comment by UserC2** [comment]
Functions exist in the code for this, currently not bound to anything (or planned to be).
