### ISSUE TITLE
Motion profiling for shooter angle

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#33]
**How does this improve the robot or repo?**
* Smoother control of shooter (and less occurrences of it slamming into the lower hard stop).

**Potential Implementation**
* Replace `PIDController` with [`ProfiledPIDController`](https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/profiled-pidcontroller.html)

**Comment by gregzetko** [comment]
We should probably also tune in a "static" hold power. See if this would this change significantly as the angle increases, and if so, implement gravity feedforward

**Comment by UserC2** [comment]
> We should probably also tune in a "static" hold power. See if this would this change significantly as the angle increases, and if so, implement gravity feedforward

The `ShooterAngle` subsystem already has gravity feedforward implemented. I tested it on Saturday (and it worked until the BAG motor burnt to a crisp).

**Comment by UserC2** [comment]
~~We could also add motion profiling to the Elevator subsystem.~~
Unnecessary; motion profile is not a particularly useful thing to have on an elevator that goes to two different positions only (although it is super easy to implement so it's not a bad thing to do).
