### ISSUE TITLE
Port swerve code from 2024 Offseason Swerve repo

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#4]
**Potential Implementation**
Add YAGSL, configure with any available swerve base (configure to final robot once base built), then copy or rewrite files from 2024 offseason repo.

**Comment by gregzetko** [comment]
I made the necessary changes to the offseason repo to use 2024 libraries on the practice swerve base

**Comment by UserC2** [comment]
> I made the necessary changes to the offseason repo to use 2024 libraries on the practice swerve base

Can you commit those changes? I'll move it over to this repo tomorrow.

**Comment by gregzetko** [comment]
I did, it's on the laptop at the school. I forgot to push, sorry :(
It has a "VisionAlignDrive" command that i used to test lining up with the limelight as seen on #programming-general disc

**Comment by UserC2** [comment]
Moved changes over from that repo.
