### ISSUE TITLE
Switch shooter angle control from absolute encoder to neo encoder

### ISSUE THREAD

**Issue by gregzetko** [frc2609/Crescendo-2024#45]
**How does this improve the robot or repo?**
Improves the stability of our shooter angle readings

**Improvement Description**
We noticed a variance in absolute encoder readings of about +- 0.5 degrees at rest, which is not stable enough for control.
The NEO encoder also has better resolution due to the gear reduction, at the expense of not seeing any slip or backlash if it happens (it probably won't with the newer iteration of the mechanism)

**Potential Implementation**
Refactor getAngle() to getAbsoluteAngle()
Replace
`double percentOutput = anglePID.calculate(getAngle().getDegrees()...`
with 
`double percentOutput = anglePID.calculate(getSparkAngle().getDegrees()..`
If the NEO encoder is greater than ~10 degrees off from the absolute encoder, raise an alert and disable setMotor() functionality.
Once an alert is raised, wait for a manual override from an operator.

**Comment by UserC2** [comment]
Might not be necessary to use NEO encoder after all, with motion profiling shooter tracks angle to +- 0.25 degrees.
Still would be a good idea to have NEO and absolute encoder checking with each other to make sure the angle hasn't deviated.
