### ISSUE TITLE
Ridiculous Loop Overruns

### ISSUE THREAD

**Issue by UserC2** [frc2609/Crescendo-2024#58]
**Bug Description**
* We have loop cycles taking ~0.15s (i.e. almost 8x as long as they're supposed to).
* This causes the motor watchdog on the drive Krakens to time out (and therefore makes driving impossible).

**Steps to Reproduce**
1. Run the code on the robot with all subsystems enabled.
2. Attempt to drive.
3. Observe the drive Krakens are blinking orange intermittently (indicating they are disabling themselves) accompanied by a loud clicking sound.

**Expected Behavior**
* Code has no loop overruns (preferably), or code has reasonable loop overruns (i.e. 0.04s, not 0.15s!)

**Ideas**
* Comment out each subsystem one by one to isolate performance-intensive subsystem, then investigate ways to make it more efficient.

**Comment by gregzetko** [comment]
Could this be because of the 
`Results results = LimeLightHelpers.getLatestResults("limelight").targetingResults;`
line in Limelight.java?

**Comment by UserC2** [comment]
[Issue #5903 in `allwpilib`](https://github.com/wpilibsuite/allwpilib/issues/5903) specifies it's not a good idea to do e.g. `if (controller.leftBumper().getAsBoolean()) ...` since every time a call like this is made, a function is added to the EventLoop in CommandScheduler to update the value of the trigger (which is only used once then discarded at the end of the expression)!

We do this in two places:
* `ShooterFlywheel` test command
* `DriveUtil::getSensitivity()` (gets called every loop cycle!)

To fix this, store the trigger in a variable, then call `getAsBoolean()` on the stored trigger.

After running the robot code for ~5 minutes:
![image](https://github.com/frc2609/Crescendo-2024/assets/85082371/df1296d3-4663-4b6a-a02b-44398bc0f184)

;)

~~(This is not the solution, but it certainly isn't helping.)~~

I lied, the event loop ends up taking ~95% of CPU time eventually (on the laptop) just absolutely full of BooleanSuppliers... this might be significant.

**Comment by UserC2** [comment]
Also, [VisualVM](https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/profiling-with-visualvm.html) is helpful in diagnosing loop overruns.

**Comment by WhyNot180** [comment]
> Could this be because of the `Results results = LimeLightHelpers.getLatestResults("limelight").targetingResults;` line in Limelight.java?

Changed all json parsing to network tables calls in commit 3a80943.
It still needs to be tested how much of an effect this will have.

**Comment by UserC2** [comment]
> > Could this be because of the `Results results = LimeLightHelpers.getLatestResults("limelight").targetingResults;` line in Limelight.java?
> 
> Changed all json parsing to network tables calls in commit [3a80943](https://github.com/frc2609/Crescendo-2024/commit/3a809439448a09733e4ac346e8c5fbcf0001b873). It still needs to be tested how much of an effect this will have.

![image](https://github.com/frc2609/Crescendo-2024/assets/85082371/a7886056-aa7e-4db2-be44-6c4187b2615c)

@WhyNot180 
@newjanson 

What do you think this does?

**Comment by WhyNot180** [comment]
> > > Could this be because of the `Results results = LimeLightHelpers.getLatestResults("limelight").targetingResults;` line in Limelight.java?
> > 
> > Changed all json parsing to network tables calls in commit [3a80943](https://github.com/frc2609/Crescendo-2024/commit/3a809439448a09733e4ac346e8c5fbcf0001b873). It still needs to be tested how much of an effect this will have.
> 
> ![image](https://github.com/frc2609/Crescendo-2024/assets/85082371/a7886056-aa7e-4db2-be44-6c4187b2615c)
> 
> @WhyNot180 
> @newjanson 
> 
> What do you think this does?

That is redundant, results.valid is equivalent to getTV (targets valid)

**Comment by UserC2** [comment]
> > > > Could this be because of the `Results results = LimeLightHelpers.getLatestResults("limelight").targetingResults;` line in Limelight.java?
> > > 
> > > 
> > > Changed all json parsing to network tables calls in commit [3a80943](https://github.com/frc2609/Crescendo-2024/commit/3a809439448a09733e4ac346e8c5fbcf0001b873). It still needs to be tested how much of an effect this will have.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/85082371/311906578-a7886056-aa7e-4db2-be44-6c4187b2615c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTk2OTYsIm5iZiI6MTcxMDIxOTM5NiwicGF0aCI6Ii84NTA4MjM3MS8zMTE5MDY1NzgtYTc4ODYwNTYtYWE3ZS00ZGIyLWJlNDQtNmM0MTg3YjI2MTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA0NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzN2RkMWUxMjc3MWYwMDVjNGQzZTc0YTM4N2Y3Y2VjZjZiZWM5M2I0OTI0Y2VlZWMxNzgyOWNjYmMyYTJhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BN_ESERpz1-nB1t8bXg4c0kzpbGnlcFZNobrxG2IfIc)
> > @WhyNot180
> > @newjanson
> > What do you think this does?
> 
> That is redundant, results.valid is equivalent to getTV (targets valid)

That's the fun part, because I've gotten it to crash the code :)

(If the Limelight is poorly tracking the AprilTags (e.g. dark room), then there's a pretty decent chance the code will eventually run into a point where the tags were visible on `LimelightHelpers.getTV(...)` and then by the next call to NetworkTables (`getLatestResults`) the Limelight loses track of the targets. Then, the exception is triggered, and goodbye robot code.)

The more useful part of this is that when this happens, odometry becomes `NaN`, which leads to the shooter angle calculated by `AutoSetShooter` to be `NaN` which leads to a fun conversation about why the robot snapped the cable chain again.

**Comment by UserC2** [comment]
Closing for now, as #84 fixed some major ones.
